version: "3"
services:
  logseq:
    build:
      context: ./
    image: seanly/appset:logseq
    restart: always
    ports:
      - 3001:80

networks:
  default:
    name: opsbox-network
    external: true
