version: "3"
services:
  vimrc:
    build: 
      context: ./vimrc
    image: seanly/vimrc

  opsbox-tool:
    build:
      context: ./
    image: seanly/opsbox-tool
    command: bash
    tty: true
    volumes:
      - ./:/ws
    restart: always
