version: "3"
services:
  vimrc:
    build: 
      context: ./vimrc
    image: seanly/vimrc

  opsbox-k3s:
    build:
      context: ./k3s
    image: seanly/k3s-dind
    volumes:
      - ./:/data
    restart: always
    privileged: true
    network_mode: host

  opsbox-tool:
    build:
      context: ./
    image: seanly/opsbox-tool
    volumes:
      - ./:/data
    restart: always
