version: "3"
services:
  vimrc:
    build: 
      context: ./toolset/vimrc
    image: seanly/toolset:vimrc

  docker:
    build: 
      context: ./toolset/docker
    image: seanly/toolset:docker
  toolset:
    build:
      context: ./
    image: seanly/opsbox:toolset
    command: bash
    tty: true
    volumes:
      - ./:/data
    restart: always
