version: "3"
services:
  toolset:
    build:
      context: ./
    image: seanly/opsbox:toolset
    tty: true
    environment:
    - DOCKER_BUILDKIT=1
    volumes:
      - ./:/ws
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: always
