version: "3"
services:
  api-testing:
    image: ghcr.io/linuxsuren/api-testing:master
    restart: always
    ports:
      - 8080:8080
      - 7070:7070

networks:
  default:
    name: opsbox-network
    external: true
