version: '3'

services:
  mysql:
    image: seanly/dbextra:mysql-5.7.35
    restart: unless-stopped
    volumes:
      - keycloak-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: keycloak@root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak_rw
      MYSQL_PASSWORD: keycloak_rw@root
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e "SHOW DATABASES;"
      interval: 3s
      timeout: 1s
      retries: 5

  keycloak:
    build:
      context: .
      args:
        KEYCLOAK_VERSION: 14.0.0
    container_name: keycloak
    image: seanly/appset:keycloak-v14.0.0-1
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:8080
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin!23
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_USER: keycloak_rw
      DB_PASSWORD: keycloak_rw@root
      JDBC_PARAMS: connectTimeout=90&useSSL=false

networks:
  default:
    name: opsbox-network
    external: true

volumes:
    keycloak-mysql:

# https://blog.please-open.it/ldap-keycloak/