apiVersion: batch/v1
kind: Job
metadata:
  name: image-syncer
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
        - name: image-syncer
          image: seanly/toolset:image-syncer
          command:
            - image-syncer
            - --auth
            - /config/auth.json
            - --images
            - /config/images.json
            - -p
            - "20"
          volumeMounts:
            - name: images-config
              mountPath: /config/images.json
              readOnly: true
              subPath: images.json
            - name: auth-config
              mountPath: /config/auth.json
              readOnly: true
              subPath: auth.json
      volumes:
        - name: images-config
          configMap:
            name: images-config
        - name: auth-config
          secret:
            secretName: auth-config
      restartPolicy: Never
