version: "3"
services:
  chatgpt:
    build:
      context: ./
      dockerfile: ./Dockerfile.chatgpt-next-web
    image: seanly/appset:chatgpt
    restart: always
    ports:
      - 3000:3000
  yakgpt:
    image: yakgpt/yakgpt:latest
    restart: always
    ports:
      - 3001:3000

networks:
  default:
    name: opsbox-network
    external: true
